Idrinth = {};

Idrinth.Constants = require("script/idrinth/constants");
Idrinth.Version = require("script/idrinth/version");
Idrinth.Names = require("script/idrinth/names");
Idrinth.Factions = require("script/idrinth/factions");
Idrinth.log = require("script/idrinth/logging");
Idrinth.Access = require("script/idrinth/access");
Idrinth.cultures = require("script/idrinth/cultures");
Idrinth.Statistics = require("script/idrinth/statistics");
Idrinth.Settings = require("script/idrinth/settings");
require("script/idrinth/utility");
require("script/idrinth/settings");
require("script/idrinth/unlocks");
require("script/idrinth/resources");
require("script/idrinth/story");
require("script/idrinth/chapels");
require("script/idrinth/interventions");
require("script/idrinth/army");
require("script/idrinth/pointsofinterest");
require("script/idrinth/renaming");
require("script/idrinth/statistics");
require("script/idrinth/traits");