files:
  - source: /idrinth/text/db/*__.loc.tsv
    translation: /%original_path%/idrinth__%two_letters_code%.loc.tsv
  - source: /idrinth/readme.steam
    translation: /idrinth/readme-%two_letters_code%.steam
