name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for finding something to improve or fix! I'll usually react within 24h."
        pr-message: "Thank you for contributing! I'll usually react within 24h."
