name: LUA
on:
  push:
    branches:
    - the-one
    paths:
    - '**.lua'
  pull_request:
    branches:
    - the-one
    paths:
    - '**.lua'
jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install lua
        run: sudo apt install lua5.1 liblua5.1-dev
      - name: Install luarocks
        run: wget https://luarocks.org/releases/luarocks-3.13.0.tar.gz && tar zxpf luarocks-3.13.0.tar.gz && cd luarocks-3.13.0 && ./configure && make && sudo make install && cd .. && rm luarocks-3.13.0.tar.gz && rm -r luarocks-3.13.0
      - name: Install luacheck
        run: sudo luarocks install luacheck
      - name: Run luacheck
        run: luacheck .
  selene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install selene
        run: |
          curl -L https://github.com/Kampfkarren/selene/releases/download/0.29.0/selene-0.29.0-linux.zip -o selene.zip
          unzip selene.zip
          chmod +x selene
          sudo mv selene /usr/local/bin/
      - name: Run selene
        run: selene .
